//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class propPlace_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public propPlace_tbl()
        {
            this.studentConstraints_tbl = new HashSet<studentConstraints_tbl>();
        }
    
        public int id_propPlace { get; set; }
        public string propPlace_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentConstraints_tbl> studentConstraints_tbl { get; set; }
        public override string ToString()
        {
            return this.propPlace_name;
        }
    }
}
