//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public class_tbl()
        {
            this.students_tbl = new HashSet<students_tbl>();
        }
    
        public int id_class { get; set; }
        public string class_name { get; set; }
        public Nullable<int> num_class_in_grade { get; set; }
        //איך להוריד את האפשרות ל-NULL
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<students_tbl> students_tbl { get; set; }
        public override string ToString()
        {
            return this.class_name.TrimEnd()+this.num_class_in_grade;
        }
    }
}
