//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Nechami_placementEntities : DbContext
    {
        public Nechami_placementEntities()
            : base("name=Nechami_placementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<class_tbl> class_tbl { get; set; }
        public virtual DbSet<propPlace_tbl> propPlace_tbl { get; set; }
        public virtual DbSet<studentConstraints_tbl> studentConstraints_tbl { get; set; }
        public virtual DbSet<students_tbl> students_tbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
